# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPost():
  def setup_method(self, method):
    self.options = webdriver.ChromeOptions()
    #self.options.add_argument('--headless')
    #self.options.add_argument('--disable-dev-shm-usage')
    #self.options.add_argument('--no-sandbox')
    self.driver = webdriver.Chrome(options = self.options)
    self.vars = {}

  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_post(self):
    self.driver.get("https://www.linkedin.com/")
    self.driver.find_element_by_

testClass = TestPost()
testClass.setup_method("")
testClass.test_post()
testClass.teardown_method("")
