# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPost():
  def setup_method(self, method):
    self.options = webdriver.ChromeOptions()
    self.options.add_argument('--headless')
    self.options.add_argument('--disable-dev-shm-usage')
    self.options.add_argument('--no-sandbox')
    self.driver = webdriver.Chrome(options = self.options)
    self.vars = {}

  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_post(self):
    self.driver.get("https://www.linkedin.com")
    self.driver.find_element_by_class_name('nav__button-secondary').click()

    self.usernameBox = self.driver.find_element_by_id('username')
    self.usernameBox.send_keys('kenrobson@icloud.com')

    self.passwordBox = self.driver.find_element_by_id('password')
    self.passwordBox.send_keys('*qs+W4:4eG2xLY?dmw7!E\'zvPJ]\whK>')

    self.signInButton = self.driver.find_element_by_class_name("btn__primary--large.from__button--floating")
    self.signInButton.click()




    #element = self.driver.find_element_by_xpath("//button[starts-with(@class, 'share-box-feed-entry') and ends-with(@class, '__trigger')]")
    #element = self.driver.find_element_by_xpath("//button[contains(@span, 'Start a post')]")
    #actions.move_to_element(element).perform()
    #self.driver.find_element(By.CSS_SELECTOR, "#ember943 > .artdeco-button__text").click()
    #element = self.driver.find_element(By.CSS_SELECTOR, ".share-creation-state__text-editor .ql-editor")
    #self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test Post Please Ignore</p>'}", element)
    #self.driver.find_element(By.CSS_SELECTOR, "#ember383 > .artdeco-button__text").click()

testClass = TestPost()
testClass.setup_method("")
testClass.test_post()
testClass.teardown_method("")
